@echo off
setlocal EnableDelayedExpansion

set PROJECT_DIR=%~dp0
set ROOT=%PROJECT_DIR%\..\..
set FEATURE_DIR=%ROOT%\Features

set DSC_OUT=%PROJECT_DIR%\Include\FeatureIncludes.dsc.inc
set FDF_OUT=%PROJECT_DIR%\Include\FeatureIncludes.fdf.inc
set FDF_RULE_OUT=%PROJECT_DIR%\Include\FeatureRuleIncludes.fdf.inc

> "%DSC_OUT%" (
    echo ## Auto-generated by GenerateFeatureIncludes.bat. Do not edit.
    echo.
)

> "%FDF_OUT%" (
    echo ## Auto-generated by GenerateFeatureIncludes.bat. Do not edit.
    echo.
)

> "%FDF_RULE_OUT%" (
    echo ## Auto-generated by GenerateFeatureIncludes.bat. Do not edit.
    echo.
)

for /d %%D in ("%FEATURE_DIR%\*") do (
    set PKG=%%~nxD
    set FEATURE=!PKG:Pkg=!

    if exist "%%D\!FEATURE!.dsc.inc" (
        echo ^^!include !PKG!/!FEATURE!.dsc.inc>>"%DSC_OUT%"
    )

    if exist "%%D\!FEATURE!.fdf.inc" (
        echo ^^!include !PKG!/!FEATURE!.fdf.inc>>"%FDF_OUT%"
    )

    if exist "%%D\!FEATURE!Rules.fdf.inc" (
        echo ^^!include !PKG!/!FEATURE!Rules.fdf.inc>>"%FDF_RULE_OUT%"
    )
)

echo Done generating feature include files.